# Generated by Django 2.2 on 2020-05-15 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('project_id', models.IntegerField()),
                ('up_votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=models.SET(8), to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='charityfinder_app.Comment')),
            ],
            options={
                'ordering': ['up_votes', 'created'],
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
