# Generated by Django 2.2 on 2020-05-11 14:29

import charityfinder_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityfinder_app', '0002_auto_20200507_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='edited_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='project_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(charityfinder_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=models.SET(charityfinder_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(on_delete=models.SET(charityfinder_app.models.get_sentinel_comment), to='charityfinder_app.Comment')),
            ],
        ),
    ]
