# Generated by Django 2.2 on 2020-05-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0003_auto_20200511_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='edited_at',
            new_name='last_edited',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='edited_at',
            new_name='last_edited',
        ),
    ]
