# Generated by Django 2.2 on 2020-05-11 15:19

import charityfinder_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0004_auto_20200511_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(default='', on_delete=models.SET(charityfinder_app.models.get_sentinel_comment), to='charityfinder_app.Comment'),
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
