# Generated by Django 2.2 on 2020-05-16 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0004_auto_20200516_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=8, on_delete=models.SET(8), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
