# Generated by Django 2.2 on 2020-05-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0010_auto_20200511_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
    ]
