# Generated by Django 2.2 on 2020-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0011_auto_20200518_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
