# Generated by Django 2.2 on 2020-05-11 15:55

import charityfinder_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0011_remove_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(default='', on_delete=models.SET(charityfinder_app.models.get_sentinel_comment), to='charityfinder_app.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(charityfinder_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
