# Generated by Django 2.2 on 2020-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0012_auto_20200518_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_to_id',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
