# Generated by Django 2.2 on 2020-05-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0013_auto_20200518_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='charityfinder_app.Comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
