# Generated by Django 2.2 on 2020-05-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0015_auto_20200518_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='up_votes',
            new_name='rated',
        ),
    ]
