# Generated by Django 2.2 on 2020-05-11 16:11

import charityfinder_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0015_auto_20200511_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(default=0, on_delete=models.SET(charityfinder_app.models.get_sentinel_comment), to='charityfinder_app.Comment'),
        ),
    ]
