# Generated by Django 2.2 on 2020-05-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0018_auto_20200519_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-rated', '-created']},
        ),
    ]
