# Generated by Django 2.2 on 2020-05-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0019_auto_20200519_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
