# Generated by Django 2.2 on 2020-05-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0020_auto_20200519_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_edited',
        ),
    ]
