# Generated by Django 2.2 on 2020-05-12 10:53

import charityfinder_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0020_auto_20200512_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=models.SET(charityfinder_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
