# Generated by Django 2.2 on 2020-05-20 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityfinder_app', '0021_remove_comment_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=1024),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rated',
        ),
        migrations.CreateModel(
            name='UserCommentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityfinder_app.Comment')),
                ('user', models.ForeignKey(on_delete=models.SET(8), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='rated',
            field=models.ManyToManyField(related_name='rated_user', through='charityfinder_app.UserCommentRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
