# Generated by Django 2.2 on 2020-05-12 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0021_auto_20200512_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=models.SET('User deleted'), to=settings.AUTH_USER_MODEL),
        ),
    ]
