# Generated by Django 2.2 on 2020-05-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0022_auto_20200520_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usercommentrating',
            name='state',
            field=models.TextField(max_length=2),
        ),
    ]
