# Generated by Django 2.2 on 2020-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0023_auto_20200521_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentrating',
            name='state',
            field=models.TextField(default=0, max_length=2),
        ),
    ]
