# Generated by Django 2.2 on 2020-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0024_auto_20200521_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentrating',
            name='state',
            field=models.SmallIntegerField(default=0),
        ),
    ]
