# Generated by Django 2.2 on 2020-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0025_auto_20200521_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommentrating',
            name='state',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
