# Generated by Django 2.2 on 2020-05-23 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityfinder_app', '0026_auto_20200522_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTotalRating',
        ),
        migrations.AddField(
            model_name='userprojectrating',
            name='project_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprojectrating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprojectrating',
            name='user',
            field=models.ForeignKey(default=8, on_delete=models.SET(8), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercommentrating',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
