# Generated by Django 2.2 on 2020-05-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityfinder_app', '0027_auto_20200523_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommentrating',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usercommentrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='UserCommentRating',
        ),
    ]
