# Generated by Django 2.2 on 2020-05-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0003_auto_20200525_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default=[], upload_to='profile_pics'),
        ),
    ]
