# Generated by Django 2.2 on 2020-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0004_auto_20200525_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='/static/user_profile_app/images/default_profile.png', upload_to='profile_pics'),
        ),
    ]
