# Generated by Django 2.2 on 2020-05-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0006_auto_20200525_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='verified_employee',
            new_name='verified_affiliated',
        ),
    ]
