# Generated by Django 2.2 on 2020-05-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0008_auto_20200525_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='/default_profile.png', upload_to=''),
        ),
    ]
